name: Build

on:
  push:

jobs:
  build:
    name: Stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v3
      - name: Cache Global Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - name: Cache Workspace Dependencies
        uses: actions/cache@v3
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-
      - name: Setup Stack
        uses: mstksg/setup-stack@v1
      - name: Install dependencies
        run: stack --no-terminal --install-ghc --resolver nightly-2023-02-09 test --bench --only-dependencies
      - name: Stack Test
        run: stack --no-terminal --resolver nightly-2023-02-09 test --bench --no-run-benchmarks --haddock --no-haddock-deps


