name: Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        plan:
        - { build: stack, resolver: "--resolver nightly-2023-02-09" }
        - { build: stack, resolver: "--resolver lts-20.13" }
        include: []
    name: Stack
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v3
      - name: Cache Global Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - name: Cache Workspace Dependencies
        uses: actions/cache@v3
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-
      - name: Setup Stack
        uses: mstksg/setup-stack@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Install dependencies
        run: |
          set -ex
          stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
          set +ex
        env:
          ARGS: ${{ matrix.plan.resolver }}
      - name: Stack Test
        run: |
          set -ex
          stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
          set +ex
        env:
          ARGS: ${{ matrix.plan.resolver }}


